### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by gouthamvel** [anilmaurya/ember-inplace-edit#1]
> Addon templates were detected, but there are no template compilers registered for `ember-inplace-edit`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ember-inplace-edit`'s `package.json`.

Found similar issues on other cli may be needs fix.

```
https://github.com/abuiles/ember-cli-101-errata/issues/180
```

Info

```
Version 
cli 0.2.7
ember: 1.12.0
```

**Comment by anilmaurya** [comment]
@gouthamvel Thanks for reporting, I will fix this soon.

**Comment by Awem** [comment]
Just tried `0.0.4` of youd addon. Nice work, but not sure why you did https://github.com/anilmaurya/ember-inplace-edit/commit/e083021d750538eea578b4d8ae7f595efb0eaff3. The problem was actually fixed with https://github.com/anilmaurya/ember-inplace-edit/commit/33f5058123f784e06e05a444fc9349b4808e9a48 which relied on `ember-cli-htmlbars` that comes with Ember CLI. https://github.com/anilmaurya/ember-inplace-edit/commit/e083021d750538eea578b4d8ae7f595efb0eaff3 actually reintroduced the issue for me, because it removed the compiler from `dependencies`. If you want to use `broccoli-ember-hbs-template-compiler`, why not list it under `dependencies` instead of `devDependencies`?

**Comment by anilmaurya** [comment]
@AW-UC https://github.com/anilmaurya/ember-inplace-edit/commit/33f5058123f784e06e05a444fc9349b4808e9a48 didn't fixed #1 for me, After https://github.com/anilmaurya/ember-inplace-edit/commit/e083021d750538eea578b4d8ae7f595efb0eaff3        it was fixed for me.

Did 0.0.4 worked for you or you had to make changes to make it work ?

**Comment by Awem** [comment]
@anilmaurya That is strange. Do you use latest Ember CLI? I installed the addon at https://github.com/anilmaurya/ember-inplace-edit/commit/33f5058123f784e06e05a444fc9349b4808e9a48. That works, latest release not. I can check tomorrow, what changes are need at the latest release. I guess you'll have to add everything related to template compiling to `dependencies`. Otherwise, those modules won't be installed on addon installation.

**Comment by anilmaurya** [comment]
@AW-UC Even I thought adding `ember-cli-htmlbars` to dependencies instead of devDependencies will fix this error, but it didn't . I am using ember-cli 0.2.7 .

**Comment by Awem** [comment]
Ok, I see. You are using a quiet old Ember CLI. I recommend that you use a recent release, so that your addon development is up to date with Ember. With `broccoli-ember-hbs-template-compiler` you are using Handlebars instead of HTMLbars.
You are also using deprecate stuff like `bind-attr` or e.g. `function(){}.property('property'),` instead of `Ember.computed('property', function(){})`. If you don't adapt your code, this addon will be unusable in future Ember releases.

**Comment by anilmaurya** [comment]
@AW-UC Thanks for follow up, we can keep this release for older version of ember-cli and release updated version for new ember cli version.

Feel free to contribute :smile:
